<?php
require_once("GlobalVariable.php");//一番最初に読み込ませる
require_once("ErrorCheck.php");
require_once("Master.php");
require_once("PostProtocol.php");
require_once("MySQLSetting.php");
require_once("APIServer.php");
require_once("ReadFile.php");
?>